server {
	listen 443 ssl;
	server_name api.shop-x.test;
	ssl_certificate /etc/letsencrypt/live/shop-x/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/shop-x/privkey.pem;
	location / {
		proxy_pass http://shop_app;
	}
}
