// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of the SSH agent the app would use.
 */
export type AgentState = "keys" | "empty" | "unavailable";
