// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `ssh-add -l` says about the agent, for Settings › About and the
 * diagnostics. Only whether an agent answers and how many keys it holds.
 */
export type AgentStatus = { 
/**
 * An agent answered (with or without keys).
 */
present: boolean, 
/**
 * The agent holds at least one key.
 */
has_keys: boolean, 
/**
 * How many keys it holds (a count only, never names or fingerprints).
 */
keys: number, };
