// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiFinding } from "./AiFinding";

/**
 * What the model made of one payload.
 */
export type AiAnalysis = { summary: string, findings: Array<AiFinding>, };
