// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked finding. `id` names a result of the payload; its severity is the
 * check's, found through the payload, not here.
 */
export type AiFinding = { id: string, why: string, 
/**
 * Text to read and copy. Never run by Daminus.
 */
suggested_command: string | null, 
/**
 * 1 is the most urgent.
 */
rank: number, };
