// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderEntry } from "./AiProviderEntry";
import type { ClaudeCodeStatus } from "./ClaudeCodeStatus";

/**
 * The provider screens' one read.
 */
export type AiProvidersView = { providers: Array<AiProviderEntry>, 
/**
 * The selected provider; `None` is AI off.
 */
provider: string | null, model: string | null, base_url: string | null, claude_code_ack: boolean, claude_code: ClaudeCodeStatus, };
