// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderProfile } from "./ProviderProfile";

/**
 * One provider tile: the profile and whether a key is stored for it (never the key).
 */
export type AiProviderEntry = { profile: ProviderProfile, key_set: boolean, };
