// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiSettings = { 
/**
 * Selected provider id; `None` = AI off (the default).
 */
provider: string | null, model: string | null, 
/**
 * The user accepted the Claude Code (Beta) warning.
 */
claude_code_acknowledged: boolean, };
