// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiFinding } from "./AiFinding";
import type { CheckKey } from "./CheckKey";
import type { ErrorCode } from "./ErrorCode";

/**
 * One event of a send, on `ai://event`. `seq` rises by one per event of a request.
 */
export type AiStreamEvent = { request_id: string, seq: number, } & ({ "kind": "summary_delta", text: string, } | { "kind": "finding", finding: AiFinding, 
/**
 * The result the id names, from the payload that was sent; none when it names none.
 */
key: CheckKey | null, } | { "kind": "done", summary: string, reviewed_sends: number, offer_turning_off_review: boolean, } | { "kind": "error", error: ErrorCode, } | { "kind": "cancelled" });
