// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * How a connection test ended.
 */
export type AiTestResult = { ok: boolean, ms: number, error: ErrorCode | null, };
