// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * The error type of every IPC command.
 */
export type AppError = { code: ErrorCode, params?: { [key in string]: string }, retryable: boolean, };
