// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type AppearanceSettings = { theme: Theme, reduce_transparency: boolean, animate_charts: boolean, clear_sky: boolean, streak_badge: boolean, completion_chime: boolean, easter_eggs: boolean, };
