// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Day } from "./Day";
import type { Timestamp } from "./Timestamp";

export type AppState = { 
/**
 * Last launch, to pick the intro stations (first run, back after days, daily).
 */
last_opened_at: Timestamp | null, 
/**
 * Clean weeks in a row (sidebar streak, one star per week).
 */
streak_weeks: number, 
/**
 * First day of the last week counted into the streak.
 */
streak_week_start: Day | null, 
/**
 * The week in `streak_week_start` had a critical finding, so it does not count.
 */
streak_week_critical: boolean, 
/**
 * AI requests sent after the payload review screen was shown.
 */
ai_reviewed_sends: number, };
