// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { FactsDoc } from "./FactsDoc";
import type { Runs } from "./Runs";
import type { SeverityRule } from "./SeverityRule";

export type CheckSpec = { id: string, group: CheckGroup, runs: Runs, 
/**
 * File in `crates/core/checks/` for remote checks. A remote check without
 * one is not in the bundle yet.
 */
script?: string | null, 
/**
 * External commands the script may run on the server. CI rejects any
 * other command (allowlist), so this is also the script's review list.
 */
needs?: Array<string>, facts?: FactsDoc, 
/**
 * How the evidence fingerprint `fp` is made, for checks with evidence.
 */
fp?: string | null, rule: SeverityRule, };
