// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group of checks that the user switches on or off as one (Settings › Scan).
 * `System` (load, memory, swap, pressure, OOM) is always on.
 */
export type CheckGroup = "system" | "disk" | "containers" | "databases" | "security" | "uptime" | "code_changes";
