// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { Runs } from "./Runs";
import type { SeverityRule } from "./SeverityRule";

export type CheckSpec = { id: string, group: CheckGroup, runs: Runs, rule: SeverityRule, };
