// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnknownReason } from "./UnknownReason";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One raw result line. Severity is not part of it: Rust grades facts at read
 * time with the manifest rule, so a threshold change needs no rescan.
 */
export type CheckFact = { 
/**
 * Check id from the manifest, e.g. `disk.fs`.
 */
check: string, 
/**
 * What was checked: a mount point, a path, a container, a URL. Empty for
 * checks with a single result per host (`sys.load`).
 */
target: string, value?: number | null, unit?: string | null, 
/**
 * Check-specific details (sizes, top lists, states). Arrays are capped at ingest.
 */
data?: JsonValue, 
/**
 * Evidence fingerprint (size + mtime + short sha256) for checks with evidence.
 */
fp?: string | null, 
/**
 * Set when the check could not answer.
 */
unknown?: UnknownReason | null, };
