// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostRef } from "./HostRef";

/**
 * Identity of a result across scans: `(host, check, target)`. URL probes run
 * from this Mac use host `@local` and the URL as target.
 */
export type CheckKey = { host: HostRef, check: string, target: string, };
