// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a measured number compares to a threshold.
 */
export type Cmp = "gt" | "gte" | "lt" | "lte";
