// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";
import type { HostAlias } from "./HostAlias";
import type { Role } from "./Role";

export type Component = { role: Role, host: HostAlias, } & ({ "kind": "path", path: string, } | { "kind": "compose", project: string, } | { "kind": "pm2", app: string, pm2_home?: string | null, } | { "kind": "db", engine: DbEngine, database?: string | null, env_file?: string | null, container?: string | null, });
