// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A docker compose project, from the labels of its containers.
 */
export type ComposeProject = { project: string, dir?: string | null, services: Array<string>, running: number, total: number, 
/**
 * Host ports its containers publish.
 */
ports: Array<number>, };
