// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";

/**
 * What a component is on its host. Written flat into the component with a
 * `kind` tag: `{"role":"fe","host":"vps-a","kind":"path","path":"/var/www/shop"}`.
 *
 * Every string here is later passed to server-side scripts and `docker exec`
 * as an argument, so loading rejects values that could be read as an option
 * or break out of an argument: names must match `[A-Za-z0-9][A-Za-z0-9._-]*`
 * and paths must be absolute with no control characters.
 */
export type ComponentKind = { "kind": "path", path: string, } | { "kind": "compose", project: string, } | { "kind": "pm2", app: string, } | { "kind": "db", engine: DbEngine, database: string, env_file: string, container?: string | null, };
