// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a config file, numbered from 1 as ssh numbers it.
 */
export type ConfigLine = { number: number, text: string, };
