// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";

/**
 * A host the user can pick.
 */
export type ConfigHost = { alias: HostAlias, 
/**
 * The file that defines it (an included file, maybe).
 */
file: string, line: number, };
