// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Counts = { crit: number, warn: number, expected: number, needs_perm: number, stale: number, 
/**
 * Unknown for reasons other than permissions.
 */
unknown: number, };
