// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataSettings = { 
/**
 * Snapshots to keep; `None` keeps all.
 */
keep_scans: number | null, 
/**
 * Days before AI replies are forgotten; `None` = never.
 */
forget_ai_after_days: number | null, };
