// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's folder in numbers.
 */
export type DataUsage = { 
/**
 * The folder as shown to the user, with `~` for the home folder.
 */
path: string, 
/**
 * JSON files in the folder: projects, settings, state and one per kept scan.
 */
files: number, 
/**
 * Kept scans.
 */
scans: number, 
/**
 * Bytes of the scan files.
 */
scans_bytes: number, 
/**
 * Bytes of projects, settings and state.
 */
config_bytes: number, 
/**
 * Bytes of the local log files.
 */
logs_bytes: number, 
/**
 * Bytes of each scan file, oldest first.
 */
scan_sizes: Array<number>, };
