// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";
import type { DbSource } from "./DbSource";

/**
 * A database server running on the host.
 */
export type DbServer = { engine: DbEngine, origin: DbSource, 
/**
 * The process name (`mariadbd`) or the container name.
 */
name: string, 
/**
 * The compose project of the container, if it has one.
 */
project?: string | null, };
