// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

/**
 * Change against the previous scan.
 */
export type Delta = { "kind": "new" } | { "kind": "fixed" } | { "kind": "still", scans_open: number, } | { "kind": "changed", from: Severity, to: Severity, };
