// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a result counts as it stands.
 */
export type Disposition = { "kind": "active" } | { "kind": "expected", rule: string, stale_since?: number | null, } | { "kind": "stale", since_seq: number, };
