// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the SSH user can use the docker daemon.
 */
export type DockerAccess = "ok" | "no_permission" | "stopped" | "missing";
