// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the list is empty.
 */
export type EmptyReason = "no_config" | "no_usable_hosts";
