// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `.env` file. Only where it is and whether it can be read; its content
 * is never read by discover.
 */
export type EnvFile = { path: string, readable: boolean, };
