// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every error the UI can be told about. Serialized with a `kind` tag.
 */
export type ErrorCode = { "kind": "ssh_auth" } | { "kind": "ssh_host_key_unknown" } | { "kind": "ssh_host_key_changed" } | { "kind": "ssh_unreachable" } | { "kind": "ssh_not_in_config" } | { "kind": "timeout" } | { "kind": "scan_in_progress" } | { "kind": "nothing_to_scan" } | { "kind": "local_network_down" } | { "kind": "scan_not_found" } | { "kind": "config_invalid", path: string, line?: number | null, } | { "kind": "ssh_config_invalid", path: string, line?: number | null, } | { "kind": "config_from_newer_version", path: string, version: number, } | { "kind": "config_changed_on_disk", path: string, } | { "kind": "store_busy" } | { "kind": "io", path: string, } | { "kind": "secret_access_denied" } | { "kind": "provider_auth" } | { "kind": "provider_rate_limit" } | { "kind": "provider_unavailable" } | { "kind": "claude_cli_not_found" } | { "kind": "claude_cli_not_logged_in" } | { "kind": "claude_cli_quota" } | { "kind": "schema_invalid" } | { "kind": "cancelled" } | { "kind": "internal" };
