// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Covers } from "./Covers";
import type { ExpectedReason } from "./ExpectedReason";
import type { HostRef } from "./HostRef";

/**
 * What the person chose in the popover.
 */
export type ExpectedDraft = { host: HostRef, check: string, target: string, reason: ExpectedReason, covers: Covers, 
/**
 * Days until the rule comes back for review; `None` is "never".
 */
review_days: number | null, note: string, };
