// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the user trusts the finding.
 */
export type ExpectedReason = "intended" | "accepted_risk" | "false_positive";
