// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Day } from "./Day";
import type { ExpectedReason } from "./ExpectedReason";
import type { HostRef } from "./HostRef";

export type ExpectedRule = { id: string, host: HostRef, check: string, target: string, 
/**
 * Evidence fingerprint when the rule covers "this file, as it is now".
 * `None` covers any evidence at the target. A different fingerprint
 * breaks the rule and the finding is reported again.
 */
fp?: string | null, reason: ExpectedReason, 
/**
 * Review date: the rule stops applying after this day (UTC).
 */
until?: Day | null, note?: string, };
