// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The file an export wrote, by name; the folder is always Downloads.
 */
export type ExportedFile = { name: string, };
