// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a check's facts carry, in words, for contributors and reviewers.
 * Documentation only: nothing is validated against it.
 */
export type FactsDoc = { target?: string, value?: string | null, unit?: string | null, data?: { [key in string]: string }, };
