// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntroMode } from "./IntroMode";

export type GeneralSettings = { 
/**
 * App language tag (`en`, `vi`).
 */
language: string, 
/**
 * Language for AI answers; `None` follows the app language.
 */
ai_language: string | null, scan_on_open: boolean, intro: IntroMode, };
