// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanSummary } from "./ScanSummary";

/**
 * The kept scans, oldest first, and what the store holds.
 */
export type HistoryView = { scans: Array<ScanSummary>, 
/**
 * The retention limit from Settings; `None` keeps every scan.
 */
keep?: number | null, 
/**
 * Size of the snapshot files on disk, in bytes.
 */
bytes: bigint, };
