// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { HostOutcome } from "./HostOutcome";

export type HostProgress = { 
/**
 * Last group that finished.
 */
step?: CheckGroup | null, facts: number, dropped: number, } & ({ "state": "queued" } | { "state": "connecting" } | { "state": "agent_wait" } | { "state": "running" } | { "state": "finished", outcome: HostOutcome, });
