// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostKeyState } from "./HostKeyState";

export type HostKeyInfo = { state: HostKeyState, 
/**
 * The key the host offers, as `ED25519 SHA256:…`; `None` when it could
 * not be read (unreachable, or reached through a proxy).
 */
offered?: string | null, 
/**
 * The keys recorded for it, same format.
 */
known: Array<string>, 
/**
 * The name known-hosts files file this host's key under (what
 * `ssh-keygen -R` takes); `None` when the lookup never resolved the host.
 */
lookup_name?: string | null, };
