// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigHost } from "./ConfigHost";
import type { EmptyReason } from "./EmptyReason";
import type { SkippedHost } from "./SkippedHost";

export type HostList = { 
/**
 * The config file exists.
 */
config_found: boolean, hosts: Array<ConfigHost>, skipped: Array<SkippedHost>, 
/**
 * Set when `hosts` is empty: the setup screen's empty state.
 */
empty?: EmptyReason | null, };
