// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostOutcome } from "./HostOutcome";

/**
 * Where a host is in the scan.
 */
export type HostState = { "state": "queued" } | { "state": "connecting" } | { "state": "agent_wait" } | { "state": "running" } | { "state": "finished", outcome: HostOutcome, };
