// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostEntry } from "./HostEntry";
import type { HostList } from "./HostList";
import type { SshConfigProblem } from "./SshConfigProblem";

/**
 * The host list with what `ssh -G` says about each host, as the setup screens read it.
 */
export type HostListing = { list: HostList, 
/**
 * One entry per listed host, in list order.
 */
entries: Array<HostEntry>, 
/**
 * `ssh` refused the config itself: no listed host can connect until the
 * named file (and line) is fixed.
 */
config_error?: SshConfigProblem, };
