// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `Host` alias from `~/.ssh/config`: `^[A-Za-z0-9][A-Za-z0-9._-]*$`.
 */
export type HostAlias = string;
