// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";

/**
 * Time one host took in a scan, measured on this Mac (`ms`) and on the
 * server for each group that finished (`steps`, from the `step` lines).
 */
export type HostTiming = { ms: number, steps?: { [key in CheckGroup]?: number }, };
