// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a fact was measured: a server alias, or `@local` for probes run from
 * this Mac. `@` is not allowed in an alias, so the two can never collide.
 */
export type HostRef = string;
