// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a host's key stands.
 */
export type HostKeyState = "known" | "unknown" | "changed";
