// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostOutcome } from "./HostOutcome";

/**
 * How one host fared in one scan.
 */
export type HostSummary = { outcome: HostOutcome, 
/**
 * Wall time on this Mac, when the scan recorded it.
 */
ms?: number | null, };
