// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeProject } from "./ComposeProject";
import type { DbServer } from "./DbServer";
import type { EnvFile } from "./EnvFile";
import type { ListenPort } from "./ListenPort";
import type { Note } from "./Note";
import type { Pm2App } from "./Pm2App";
import type { Pm2Home } from "./Pm2Home";
import type { Vhost } from "./Vhost";

/**
 * What one host's discover run found, by kind.
 */
export type HostDiscovery = { vhosts: Array<Vhost>, compose: Array<ComposeProject>, pm2: Array<Pm2App>, pm2_homes: Array<Pm2Home>, dbs: Array<DbServer>, envs: Array<EnvFile>, ports: Array<ListenPort>, notes: Array<Note>, };
