// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";
import type { HostDiscovery } from "./HostDiscovery";
import type { HostKeyInfo } from "./HostKeyInfo";
import type { HostOutcome } from "./HostOutcome";
import type { LoginResult } from "./LoginResult";
import type { ResolvedHost } from "./ResolvedHost";

/**
 * Everything known about one host from the setup runs so far.
 */
export type HostSetup = { host: HostAlias, 
/**
 * How the last run on this host ended.
 */
outcome: HostOutcome | null, 
/**
 * What `ssh -G` says the connection uses.
 */
resolved: ResolvedHost | null, 
/**
 * Set when the host key is not accepted yet (or changed).
 */
host_key: HostKeyInfo | null, login: LoginResult | null, discovery: HostDiscovery | null, };
