// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-host settings (Settings › Hosts). Connection details stay in `~/.ssh/config`.
 */
export type HostSettings = { 
/**
 * Include in scans. Excluded hosts show "not scanned" on their projects.
 */
include: boolean, };
