// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigHost } from "./ConfigHost";
import type { ResolvedHost } from "./ResolvedHost";

/**
 * A listed host with what ssh resolves for it.
 */
export type HostEntry = { host: ConfigHost, resolved: ResolvedHost | null, };
