// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which part of the project an issue is about.
 */
export type IssueField = { "kind": "id" } | { "kind": "name" } | { "kind": "url", index: number, } | { "kind": "component", index: number, } | { "kind": "project" };
