// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrlWarning } from "./UrlWarning";

export type IssueCode = { "kind": "empty" } | { "kind": "bad_id" } | { "kind": "duplicate_id" } | { "kind": "url_invalid" } | { "kind": "url_local_only", warning: UrlWarning, } | { "kind": "url_duplicate" } | { "kind": "component_duplicate" } | { "kind": "unknown_host" } | { "kind": "replaces_existing" };
