// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFact } from "./CheckFact";
import type { CheckGroup } from "./CheckGroup";
import type { CheckKey } from "./CheckKey";
import type { Delta } from "./Delta";
import type { Disposition } from "./Disposition";
import type { Owner } from "./Owner";
import type { Severity } from "./Severity";

export type Item = { key: CheckKey, group: CheckGroup, owner: Owner, severity: Severity, disposition: Disposition, delta?: Delta | null, 
/**
 * The fact behind the severity: the latest one, or the last checked one when stale.
 */
fact?: CheckFact | null, 
/**
 * Scan in which the result was last really checked.
 */
checked_seq?: number | null, 
/**
 * An expected rule on this key whose evidence changed ("was expected, now different").
 */
rule_broken?: string | null, };
