// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchKind } from "./LaunchKind";
import type { Timestamp } from "./Timestamp";

/**
 * What a launch found: the journey and when the app was last opened.
 */
export type LaunchInfo = { kind: LaunchKind, previous: Timestamp | null, };
