// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A graded level produced by a severity rule. `Unknown` is never a rule output.
 */
export type Level = "ok" | "info" | "warn" | "crit";
