// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bind } from "./Bind";

/**
 * A listening TCP port.
 */
export type ListenPort = { port: number, bind: Bind, 
/**
 * The process that holds it, when it is one of the SSH user's own.
 */
proc?: string | null, 
/**
 * That process's working folder.
 */
cwd?: string | null, };
