// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerAccess } from "./DockerAccess";

/**
 * The login test: who the SSH user is on this host and what it may do.
 */
export type LoginReport = { 
/**
 * `uname -s`; Daminus v0.1 supports `Linux`.
 */
os: string, kernel: string, arch: string, 
/**
 * `PRETTY_NAME` of `/etc/os-release`.
 */
distro: string, user: string, uid: number, root: boolean, docker_group: boolean, 
/**
 * Can read system logs (`/var/log`).
 */
adm_group: boolean, 
/**
 * Can read the systemd journal.
 */
journal_group: boolean, docker: DockerAccess, 
/**
 * `find` is GNU find (the security checks need it).
 */
gnu_find: boolean, };
