// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginReport } from "./LoginReport";
import type { PathCheck } from "./PathCheck";

/**
 * What one host's login test found.
 */
export type LoginResult = { login: LoginReport | null, 
/**
 * The project folders that were asked about.
 */
paths: Array<PathCheck>, };
