// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckKey } from "./CheckKey";
import type { Severity } from "./Severity";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The one issue a card leads with. The UI words it from `key.check` + `params`.
 */
export type MainIssue = { key: CheckKey, params: { [key in string]: JsonValue }, severity: Severity, };
