// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckSpec } from "./CheckSpec";

export type Manifest = { checks: Array<CheckSpec>, };
