// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelSource } from "./ModelSource";

export type ModelList = { models: Array<string>, source: ModelSource, 
/**
 * The UI offers a free-text model field.
 */
manual_entry: boolean, };
