// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Network-level reason a host could not be reached.
 */
export type NetCause = "dns" | "refused" | "no_route" | "connect_timeout" | "other";
