// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteCode = "docker_no_permission" | "docker_stopped" | "pm2_missing" | "nginx_no_permission";
