// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCode } from "./NoteCode";

/**
 * A source discover could not read, so what it lists is incomplete.
 */
export type Note = { code: NoteCode, };
