// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostRef } from "./HostRef";

/**
 * Who a result belongs to, so each issue is counted once.
 */
export type Owner = { "kind": "project", id: string, } | { "kind": "server", host: HostRef, };
