// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathState } from "./PathState";

/**
 * A project folder the login test was asked about.
 */
export type PathCheck = { path: string, state: PathState, };
