// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionInfo } from "./SectionInfo";

/**
 * The text that would be sent, for display, and the hash that lets `ai_analyze` send exactly it.
 */
export type PayloadPreview = { sections: Array<SectionInfo>, system: string, user: string, total_bytes: number, hash: string, 
/**
 * How many names are hidden behind placeholders.
 */
alias_table_count: number, };
