// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pm2App = { app: string, 
/**
 * The daemon's `PM2_HOME`.
 */
home: string, 
/**
 * It is the SSH user's own daemon (`$PM2_HOME` or `~/.pm2`).
 */
default: boolean, instances: number, 
/**
 * One of pm2's own states, or `unknown`.
 */
status: string, cwd?: string | null, };
