// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pm2HomeState } from "./Pm2HomeState";

/**
 * A pm2 daemon this user may not ask.
 */
export type Pm2Home = { home: string, state: Pm2HomeState, };
