// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionId } from "./SectionId";

/**
 * The review sheet's choices.
 */
export type PreviewOptions = { question: string, 
/**
 * Sections to send; the question is always sent.
 */
include: Array<SectionId>, hide_hosts: boolean, };
