// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";

/**
 * What a question is about.
 */
export type PreviewScope = { "kind": "whole" } | { "kind": "project", id: string, } | { "kind": "server", host: HostAlias, };
