// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueCode } from "./IssueCode";
import type { IssueField } from "./IssueField";
import type { IssueLevel } from "./IssueLevel";

/**
 * One thing to tell the user about a project.
 */
export type ProjectIssue = { 
/**
 * The project's id (what the user typed, so possibly empty or taken).
 */
project: string, field: IssueField, level: IssueLevel, code: IssueCode, };
