// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";
import type { ThresholdOverride } from "./ThresholdOverride";

export type Project = { id: string, name: string, color?: string | null, 
/**
 * Checked from this Mac (`url.*`).
 */
urls: Array<string>, components: Array<Component>, 
/**
 * Threshold overrides for this project's results (project sheet).
 */
overrides?: Array<ThresholdOverride>, };
