// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpectedRule } from "./ExpectedRule";
import type { HostAlias } from "./HostAlias";
import type { HostSettings } from "./HostSettings";
import type { Project } from "./Project";

/**
 * The whole `projects.json`.
 */
export type ProjectsFile = { version: number, projects: Array<Project>, hosts: { [key in HostAlias]: HostSettings }, 
/**
 * "Mark as expected" rules. Kept here, not in snapshots, so they survive every scan.
 */
rules: Array<ExpectedRule>, };
