// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { HostAlias } from "./HostAlias";
import type { Level } from "./Level";
import type { MainIssue } from "./MainIssue";

export type ProjectRollup = { id: string, 
/**
 * Worst open issue; expected and needs-permission results never colour it.
 */
level: Level, counts: Counts, main_issue?: MainIssue | null, 
/**
 * Hosts of this project that did not answer the latest scan (a card state of its own).
 */
unreachable_hosts: Array<HostAlias>, 
/**
 * Hosts of this project left out of the latest scan (excluded or not asked).
 */
not_scanned_hosts: Array<HostAlias>, };
