// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Level } from "./Level";

/**
 * One project as one scan saw it: open issues by level, and the worst level
 * of each check that produced a result (a check that did not run is absent).
 */
export type ProjectSummary = { id: string, crit: number, warn: number, info: number, checks: { [key in string]: Level }, };
