// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbEngine } from "./DbEngine";

/**
 * What kind of part a suggested component is. As [`ComponentKind`], but a
 * database may still lack its name.
 */
export type ProposedKind = { "kind": "path", path: string, } | { "kind": "compose", project: string, } | { "kind": "pm2", app: string, pm2_home?: string | null, } | { "kind": "db", engine: DbEngine, env_file: string, container?: string | null, };
