// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedProject } from "./ProposedProject";
import type { Unassigned } from "./Unassigned";

/**
 * The suggestion: projects, and "Not in a project".
 */
export type Proposal = { projects: Array<ProposedProject>, unassigned: Array<Unassigned>, };
