// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedComponent } from "./ProposedComponent";
import type { ProposedEnv } from "./ProposedEnv";

export type ProposedProject = { id: string, name: string, 
/**
 * The public addresses of its server blocks.
 */
urls: Array<string>, components: Array<ProposedComponent>, 
/**
 * Every `.env` that sits in it, the one a database component uses included.
 */
env_files: Array<ProposedEnv>, };
