// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";

/**
 * A `.env` file found in a suggested project.
 */
export type ProposedEnv = { host: HostAlias, path: string, readable: boolean, };
