// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The hint shown on a provider tile.
 */
export type ProviderTag = "recommended" | "free_local" | "beta";
