// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { ProviderTag } from "./ProviderTag";

export type ProviderProfile = { id: string, name: string, kind: ProviderKind, 
/**
 * The `genai` adapter for `GenaiAdapter` profiles.
 */
adapter?: string | null, 
/**
 * Default endpoint; empty when the user must supply one (or there is none).
 */
base_url: string, needs_key: boolean, 
/**
 * What the key starts with, shown as a placeholder.
 */
key_hint?: string | null, 
/**
 * Suggested models, the first being the default.
 */
models: Array<string>, tag?: ProviderTag | null, };
