// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { Counts } from "./Counts";
import type { Item } from "./Item";
import type { ProjectRollup } from "./ProjectRollup";
import type { ServerRollup } from "./ServerRollup";
import type { Timestamp } from "./Timestamp";

export type Report = { 
/**
 * Latest scan number; `None` before the first scan.
 */
seq?: number | null, scanned_at?: Timestamp | null, evaluated_at: Timestamp, items: Array<Item>, projects: Array<ProjectRollup>, servers: Array<ServerRollup>, 
/**
 * Groups switched off in Settings: not evaluated, shown as "off in Settings".
 */
disabled_groups: Array<CheckGroup>, 
/**
 * Expected rules past their review date; they no longer apply.
 */
rules_due: Array<string>, 
/**
 * Every item counted once.
 */
counts: Counts, };
