// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the connection to a host really uses, as `ssh -G` computes it.
 */
export type ResolvedHost = { hostname: string, user?: string | null, port: number, identity_files: Array<string>, proxy_jump?: string | null, 
/**
 * A `ProxyCommand` is set (the connection does not go straight to the host).
 */
proxy_command: boolean, 
/**
 * The files ssh looks the host key up in: the user's, then the system's.
 */
known_hosts_files: Array<string>, host_key_alias?: string | null, 
/**
 * An `IdentityAgent` other than the default socket (1Password, Secretive…).
 */
identity_agent?: string | null, };
