// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectIssue } from "./ProjectIssue";

/**
 * What [`SetupService::save`] did.
 */
export type SaveOutcome = { "status": "saved", issues: Array<ProjectIssue>, 
/**
 * Projects in the file now.
 */
projects: number, } | { "status": "rejected", issues: Array<ProjectIssue>, };
