// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multiplies thresholds by a fact field before comparing.
 */
export type Scale = "cores";
