// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";

/**
 * What the user asked to scan. Empty = everything.
 */
export type ScanScope = { 
/**
 * Project ids: their hosts and URLs.
 */
projects: Array<string>, 
/**
 * Single hosts, scanned even when excluded in Settings › Hosts (the user
 * named them). No URLs come with them.
 */
hosts: Array<HostAlias>, };
