// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostProgress } from "./HostProgress";
import type { HostRef } from "./HostRef";
import type { Timestamp } from "./Timestamp";

/**
 * The scan in progress, as `ScanService::status` returns it.
 */
export type ScanRun = { scan_id: string, started_at: Timestamp, hosts: { [key in HostRef]?: HostProgress }, };
