// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostProgress } from "./HostProgress";
import type { HostRef } from "./HostRef";
import type { Timestamp } from "./Timestamp";

/**
 * The scan in progress, as `ScanService::status` returns it.
 */
export type ScanRun = { scan_id: string, started_at: Timestamp, 
/**
 * `seq` of the next event: every event before it is folded in here, so
 * a listener that reads the status mid-scan skips events below it.
 */
next_seq: number, hosts: { [key in HostRef]?: HostProgress }, };
