// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFact } from "./CheckFact";
import type { HostRef } from "./HostRef";
import type { Timestamp } from "./Timestamp";

/**
 * A raw fact with the scan it came from.
 */
export type ScanFact = { seq: number, at: Timestamp, host: HostRef, fact: CheckFact, };
