// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { ThresholdOverride } from "./ThresholdOverride";

export type ScanSettings = { 
/**
 * Check groups switched off. `system` cannot be switched off and is ignored here.
 */
disabled_groups: Array<CheckGroup>, 
/**
 * Paths skipped by `du` and file checks.
 */
skip_paths: Array<string>, 
/**
 * Floor for the large-files list, in MB.
 */
large_file_mb: number, 
/**
 * SSH connect timeout in seconds (Settings › Scan offers 5 / 10 / 30).
 * Only the TCP connect and handshake; each reachable host then has a
 * fixed 90 s budget for its bundle.
 */
connect_timeout_s: number, 
/**
 * Hosts scanned at once (1 / 2 / 4); `None` = Auto, the number of hosts
 * capped at 8.
 */
hosts_at_once: number | null, 
/**
 * Threshold overrides on top of the manifest (disk, container memory, certificate, restarts).
 */
thresholds: Array<ThresholdOverride>, };
