// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { HostRef } from "./HostRef";
import type { HostSummary } from "./HostSummary";
import type { ProjectSummary } from "./ProjectSummary";
import type { Timestamp } from "./Timestamp";

/**
 * One kept scan.
 */
export type ScanSummary = { seq: number, started_at: Timestamp, finished_at: Timestamp, hosts: { [key in HostRef]?: HostSummary }, 
/**
 * Open issues across everything, expected ones apart.
 */
counts: Counts, info: number, projects: Array<ProjectSummary>, };
