// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { CheckFact } from "./CheckFact";
import type { CheckGroup } from "./CheckGroup";
import type { HostOutcome } from "./HostOutcome";
import type { HostRef } from "./HostRef";

/**
 * Serialized with a `kind` tag.
 */
export type ScanEventBody = { "kind": "host_started", host: HostRef, } | { "kind": "agent_wait", host: HostRef, } | { "kind": "host_running", host: HostRef, } | { "kind": "step", host: HostRef, group: CheckGroup, ms: number, } | { "kind": "fact", host: HostRef, fact: CheckFact, } | { "kind": "host_finished", host: HostRef, outcome: HostOutcome, 
/**
 * Wall time on this Mac.
 */
ms: number, facts: number, 
/**
 * Lines rejected by the parser.
 */
dropped: number, } | { "kind": "done", snapshot_seq: number, } | { "kind": "cancelled" } | { "kind": "failed", error: AppError, };
