// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckGroup } from "./CheckGroup";
import type { ThresholdOverride } from "./ThresholdOverride";

export type ScanSettings = { 
/**
 * Check groups switched off. `system` cannot be switched off and is ignored here.
 */
disabled_groups: Array<CheckGroup>, 
/**
 * Paths skipped by `du` and file checks.
 */
skip_paths: Array<string>, 
/**
 * Floor for the large-files list, in MB.
 */
large_file_mb: number, 
/**
 * Seconds to wait for a host before it is marked unreachable.
 */
host_wait_s: number, 
/**
 * Hosts scanned at once; `None` = the engine default. Written as `null`
 * (not omitted) because the default is not `None`.
 */
hosts_at_once: number | null, 
/**
 * Threshold overrides on top of the manifest (disk, container memory, certificate, restarts).
 */
thresholds: Array<ThresholdOverride>, };
