// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `start` did.
 */
export type ScanStarted = { scan_id: string, 
/**
 * A scan was already running; this is its id and nothing new started.
 */
joined: boolean, };
