// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One part of the data. The order here is the order in the JSON.
 */
export type SectionId = "question" | "project_config" | "check_results" | "diff" | "server_facts" | "top_disk_paths";
