// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionId } from "./SectionId";

/**
 * A section as the screen lists it.
 */
export type SectionInfo = { id: SectionId, 
/**
 * Whether it is part of the bytes. A section left out still shows its size.
 */
included: boolean, 
/**
 * Bytes it takes in the data (the sizes of the included sections add up to
 * `Payload::data_bytes`; the braces and commas of the object are counted in them).
 */
bytes: number, 
/**
 * Rows it holds (1 for the question).
 */
items: number, 
/**
 * Rows dropped to keep the data under [`MAX_DATA_BYTES`].
 */
omitted: number, };
