// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { HostAlias } from "./HostAlias";
import type { HostOutcome } from "./HostOutcome";
import type { Level } from "./Level";
import type { MainIssue } from "./MainIssue";
import type { Timestamp } from "./Timestamp";

export type ServerRollup = { host: HostAlias, 
/**
 * Outcome in the latest scan; `None` when the host was not part of it.
 */
outcome?: HostOutcome | null, included: boolean, 
/**
 * Last scan that reached the host, and when it finished.
 */
last_reached_seq?: number | null, last_reached_at?: Timestamp | null, 
/**
 * Over every result on the host, whoever owns it.
 */
level: Level, counts: Counts, main_issue?: MainIssue | null, 
/**
 * Ids of projects with a component on this host.
 */
used_by: Array<string>, };
