// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSettings } from "./AiSettings";
import type { AppearanceSettings } from "./AppearanceSettings";
import type { DataSettings } from "./DataSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { ScanSettings } from "./ScanSettings";

export type Settings = { version: number, general: GeneralSettings, appearance: AppearanceSettings, scan: ScanSettings, ai: AiSettings, data: DataSettings, };
