// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { HostAlias } from "./HostAlias";
import type { HostKeyInfo } from "./HostKeyInfo";
import type { HostOutcome } from "./HostOutcome";
import type { SetupRecord } from "./SetupRecord";

/**
 * One event. `seq` rises by one per event within a run.
 */
export type SetupEvent = { setup_id: string, seq: number, } & ({ "kind": "host_started", host: HostAlias, } | { "kind": "agent_wait", host: HostAlias, } | { "kind": "host_running", host: HostAlias, } | { "kind": "item", host: HostAlias, item: SetupRecord, } | { "kind": "host_key", host: HostAlias, info: HostKeyInfo, } | { "kind": "host_finished", host: HostAlias, outcome: HostOutcome, 
/**
 * Wall time on this Mac.
 */
ms: number, items: number, 
/**
 * Lines rejected by the parser.
 */
dropped: number, } | { "kind": "done" } | { "kind": "cancelled" } | { "kind": "failed", error: AppError, });
