// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeProject } from "./ComposeProject";
import type { DbServer } from "./DbServer";
import type { EnvFile } from "./EnvFile";
import type { ListenPort } from "./ListenPort";
import type { LoginReport } from "./LoginReport";
import type { Note } from "./Note";
import type { PathCheck } from "./PathCheck";
import type { Pm2App } from "./Pm2App";
import type { Pm2Home } from "./Pm2Home";
import type { Vhost } from "./Vhost";

/**
 * One line of discover or login output.
 */
export type SetupRecord = { "rec": "login" } & LoginReport | { "rec": "path" } & PathCheck | { "rec": "vhost" } & Vhost | { "rec": "compose" } & ComposeProject | { "rec": "pm2" } & Pm2App | { "rec": "pm2_home" } & Pm2Home | { "rec": "db" } & DbServer | { "rec": "env" } & EnvFile | { "rec": "port" } & ListenPort | { "rec": "note" } & Note;
