// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";
import type { SetupHostProgress } from "./SetupHostProgress";
import type { SetupStep } from "./SetupStep";
import type { Timestamp } from "./Timestamp";

/**
 * The run in progress, as `SetupService::status` returns it.
 */
export type SetupRun = { setup_id: string, step: SetupStep, started_at: Timestamp, 
/**
 * `seq` of the next event: every event before it is folded in here.
 */
next_seq: number, hosts: { [key in HostAlias]: SetupHostProgress }, };
