// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSetup } from "./HostSetup";
import type { Proposal } from "./Proposal";

/**
 * What the runs found: per host, and the suggested projects from every host
 * that has been discovered.
 */
export type SetupResult = { hosts: Array<HostSetup>, proposal: Proposal | null, };
