// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `start` did.
 */
export type SetupStarted = { setup_id: string, 
/**
 * A run was already going; this is its id and nothing new started.
 */
joined: boolean, };
