// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnknownReason } from "./UnknownReason";

/**
 * Severity of a check result, as shown to the user.
 *
 * Serialized as `{"level":"warn"}` or `{"level":"unknown","reason":"needs_perm"}`.
 */
export type Severity = { "level": "ok" } | { "level": "info" } | { "level": "warn" } | { "level": "crit" } | { "level": "unknown", "reason": UnknownReason };
