// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cmp } from "./Cmp";
import type { Level } from "./Level";
import type { Scale } from "./Scale";

/**
 * One severity rule from the manifest. Serialized with a `type` tag.
 */
export type SeverityRule = { "type": "threshold", field: string, warn: number, crit?: number | null, cmp: Cmp, scale?: Scale | null, } | { "type": "max_of", rules: Array<SeverityRule>, } | { "type": "present", severity: Level, } | { "type": "state_map", field: string, map: { [key in string]: Level }, 
/**
 * Level for a state missing from `map`.
 */
default: Level, } | { "type": "increase", field: string, severity: Level, min: number, } | { "type": "days_left", warn: number, crit: number, flags?: Array<string>, } | { "type": "info" };
