// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a `Host` entry is not offered.
 */
export type SkipReason = "wildcard" | "match" | "no_host_name" | "invalid_alias";
