// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReason } from "./SkipReason";

/**
 * An entry that is left out, as written in the file.
 */
export type SkippedHost = { pattern: string, reason: SkipReason, file: string, line: number, };
