// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFact } from "./CheckFact";
import type { CheckGroup } from "./CheckGroup";
import type { HostOutcome } from "./HostOutcome";
import type { HostRef } from "./HostRef";
import type { Timestamp } from "./Timestamp";

export type Snapshot = { v: number, 
/**
 * Scan number, assigned by the store when the snapshot is saved.
 */
seq: number, started_at: Timestamp, finished_at: Timestamp, 
/**
 * Hash of the check bundle that ran, to tell apart results of different check versions.
 */
bundle_hash: string, hosts: { [key in HostRef]?: HostOutcome }, 
/**
 * Check groups each host finished (`step` lines). `@local` covers `uptime`.
 */
coverage: { [key in HostRef]?: Array<CheckGroup> }, facts: { [key in HostRef]?: Array<CheckFact> }, };
