// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ConfigLine } from "./ConfigLine";

/**
 * A config `ssh` refused, with the refused line quoted so the person sees
 * what to fix.
 */
export type SshConfigProblem = { 
/**
 * `ssh_config_invalid`, with the file and the line when ssh named one.
 */
error: AppError, 
/**
 * The refused line and one line each side, in file order. Empty when
 * ssh named no line or the file cannot be read; nothing else of the file
 * is ever sent.
 */
excerpt: Array<ConfigLine>, };
