// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentState } from "./AgentState";

export type SshEnvironment = { agent: AgentState, 
/**
 * Keys the agent holds (their count only, never their names or contents).
 */
keys: number, 
/**
 * `Termius.app` is installed.
 */
termius_installed: boolean, };
