// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user threshold for one check, from Settings › Scan or a project sheet.
 * `field` narrows it to rules on that field; otherwise it applies to every
 * thresholded rule of the check. `min` sets `increase` rules.
 */
export type ThresholdOverride = { check: string, field?: string | null, warn?: number | null, crit?: number | null, min?: number | null, };
