// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UTC instant, serialized as RFC 3339 (`2026-09-26T06:42:00Z`).
 */
export type Timestamp = string;
