// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostAlias } from "./HostAlias";
import type { SetupRecord } from "./SetupRecord";

/**
 * Something discover found that no suggested project owns.
 */
export type Unassigned = { host: HostAlias, 
/**
 * A `vhost`, `compose`, `pm2`, `db` or `env` record.
 */
item: SetupRecord, };
