// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a check could not produce a real answer.
 */
export type UnknownReason = "needs_perm" | "timeout" | "unreachable" | "missing" | "unsupported";
