// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrlFailure } from "./UrlFailure";

export type UrlCheck = { 
/**
 * HTTP status, when an answer came.
 */
status: number | null, 
/**
 * Milliseconds to the response header.
 */
ms: number | null, 
/**
 * Days left on the certificate (negative once expired); `https` only.
 */
tls_days: number | null, failure: UrlFailure | null, };
