// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a URL could not be fetched, as the sheet words it.
 */
export type UrlFailure = "invalid" | "dns" | "no_route" | "refused" | "timeout" | "tls" | "redirects" | "other";
