// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a URL is only reachable from here.
 */
export type UrlWarning = "loopback" | "private_network" | "link_local";
