// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An nginx `server` block.
 */
export type Vhost = { 
/**
 * The config file it is in.
 */
file: string, 
/**
 * `server_name` values (wildcards and `_` included; the grouping decides).
 */
names: Array<string>, root?: string | null, 
/**
 * `proxy_pass` as `host[:port]` (scheme and path dropped, an `upstream`
 * name resolved to its first server).
 */
proxy?: string | null, ssl: boolean, 
/**
 * `fastcgi_pass` is used (PHP-FPM).
 */
php: boolean, listen: Array<number>, };
